### ISSUE TITLE
为什么用不了了

### ISSUE THREAD

**Issue by Janmdis** [GodofOrange/rtvue-form#4]
大佬旧版本还能用么？

**Comment by ZestfulCitrus** [comment]
等我开发完吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月7日(周三) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [GodofOrange/rtvue-lowcode] 为什么用不了了 (Issue #4)




 
大佬旧版本还能用么？

**Comment by Janmdis** [comment]
能问下啥时开发完吗？

**Comment by ZestfulCitrus** [comment]
我读研比较忙，有空就会写写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月7日(周三) 晚上6:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GodofOrange/rtvue-lowcode] 为什么用不了了 (Issue #4)




 
能问下啥时开发完吗？

**Comment by Janmdis** [comment]
那老大还是学业为重吧
